# Generated by Django 4.2.6 on 2023-11-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=64)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('nacionalidad', models.CharField(max_length=64)),
                ('ciudad', models.CharField(max_length=64)),
                ('telefono', models.IntegerField()),
                ('nombreempresa', models.CharField(max_length=100)),
                ('cbu', models.IntegerField()),
                ('titular', models.CharField(max_length=64)),
                ('descripcionempresa', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('important', models.BooleanField(default=False)),
                ('cat', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
